import connectDB from "@/lib/db";
import Product from "@/models/Product";

export async function GET() {
  await connectDB();

  await Product.deleteMany({});

  await Product.insertMany([
  {
    title: "Wireless Mouse",
    description: "Ergonomic wireless mouse with USB receiver.",
    price: 19.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=1",
  },
  {
    title: "Gaming Keyboard",
    description: "RGB mechanical gaming keyboard.",
    price: 59.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=2",
  },
  {
    title: "Bluetooth Speaker",
    description: "Portable waterproof Bluetooth speaker.",
    price: 34.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=3",
  },
  {
    title: "Noise Cancelling Headphones",
    description: "Premium over-ear wireless headphones.",
    price: 129.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=4",
  },
  {
    title: "Smart Watch",
    description: "Fitness tracking smartwatch with heart rate monitor.",
    price: 149.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=5",
  },
  {
    title: "Men's Hoodie",
    description: "Comfortable cotton hoodie for everyday wear.",
    price: 39.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=6",
  },
  {
    title: "Women's Jacket",
    description: "Stylish lightweight jacket.",
    price: 69.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=7",
  },
  {
    title: "Running Shoes",
    description: "Breathable sports shoes for running.",
    price: 89.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=8",
  },
  {
    title: "Leather Wallet",
    description: "Premium genuine leather wallet.",
    price: 29.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=9",
  },
  {
    title: "Classic Sunglasses",
    description: "UV-protected stylish sunglasses.",
    price: 24.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=10",
  },
  {
    title: "Coffee Maker",
    description: "Automatic drip coffee machine.",
    price: 79.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=11",
  },
  {
    title: "Vacuum Cleaner",
    description: "Powerful bagless vacuum cleaner.",
    price: 139.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=12",
  },
  {
    title: "LED Desk Lamp",
    description: "Adjustable brightness desk lamp.",
    price: 27.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=13",
  },
  {
    title: "Wall Clock",
    description: "Modern silent wall clock.",
    price: 22.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=14",
  },
  {
    title: "Throw Pillow",
    description: "Soft decorative cushion.",
    price: 16.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=15",
  },
  {
    title: "Yoga Mat",
    description: "Non-slip exercise yoga mat.",
    price: 31.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=16",
  },
  {
    title: "Football",
    description: "Official size training football.",
    price: 25.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=17",
  },
  {
    title: "Tennis Racket",
    description: "Lightweight professional racket.",
    price: 89.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=18",
  },
  {
    title: "Camping Tent",
    description: "4-person waterproof camping tent.",
    price: 159.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=19",
  },
  {
    title: "Dumbbell Set",
    description: "Adjustable home workout dumbbells.",
    price: 119.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=20",
  },
  {
    title: "Cookbook",
    description: "Delicious recipes from around the world.",
    price: 18.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=21",
  },
  {
    title: "JavaScript Guide",
    description: "Complete JavaScript programming book.",
    price: 34.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=22",
  },
  {
    title: "Notebook",
    description: "Hardcover lined notebook.",
    price: 9.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=23",
  },
  {
    title: "Fantasy Novel",
    description: "Epic fantasy adventure story.",
    price: 14.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=24",
  },
  {
    title: "Children's Story Book",
    description: "Illustrated bedtime stories.",
    price: 12.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=25",
  },
  {
    title: "Lipstick Set",
    description: "Long-lasting matte lipstick collection.",
    price: 24.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=26",
  },
  {
    title: "Face Wash",
    description: "Gentle daily facial cleanser.",
    price: 14.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=27",
  },
  {
    title: "Perfume",
    description: "Fresh floral fragrance.",
    price: 49.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=28",
  },
  {
    title: "Hair Dryer",
    description: "Professional salon hair dryer.",
    price: 54.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=29",
  },
  {
    title: "Skin Care Kit",
    description: "Complete daily skincare routine.",
    price: 69.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=30",
  },
  {
    title: "Toy Car",
    description: "Die-cast collectible toy car.",
    price: 11.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=31",
  },
  {
    title: "Building Blocks",
    description: "Creative construction toy set.",
    price: 39.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=32",
  },
  {
    title: "Stuffed Teddy Bear",
    description: "Soft plush teddy bear.",
    price: 21.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=33",
  },
  {
    title: "Puzzle Game",
    description: "1000-piece family puzzle.",
    price: 19.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=34",
  },
  {
    title: "Remote Control Drone",
    description: "Beginner-friendly camera drone.",
    price: 199.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=35",
  },
  {
    title: "Office Chair",
    description: "Ergonomic adjustable office chair.",
    price: 179.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=36",
  },
  {
    title: "Wooden Study Desk",
    description: "Minimalist wooden computer desk.",
    price: 249.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=37",
  },
  {
    title: "Bookshelf",
    description: "5-tier wooden bookshelf.",
    price: 129.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=38",
  },
  {
    title: "Dining Chair",
    description: "Comfortable modern dining chair.",
    price: 79.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=39",
  },
  {
    title: "Bean Bag",
    description: "Large soft bean bag for relaxing.",
    price: 59.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=40",
  },
]);

  return Response.json({
    message: "Database seeded successfully",
  });
}