import connectDB from "@/lib/db";
import Product from "@/models/Product";

export async function GET() {
  await connectDB();

  await Product.deleteMany({});

  await Product.insertMany([
  {
    title: "Wireless Mouse",
    description: "Ergonomic wireless mouse with USB receiver.",
    price: 19.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=1",
  },
  {
    title: "Gaming Keyboard",
    description: "RGB mechanical gaming keyboard.",
    price: 59.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=2",
  },
  {
    title: "Bluetooth Speaker",
    description: "Portable waterproof Bluetooth speaker.",
    price: 34.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=3",
  },
  {
    title: "Noise Cancelling Headphones",
    description: "Premium over-ear wireless headphones.",
    price: 129.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=4",
  },
  {
    title: "Smart Watch",
    description: "Fitness tracking smartwatch with heart rate monitor.",
    price: 149.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=5",
  },
  {
    title: "Men's Hoodie",
    description: "Comfortable cotton hoodie for everyday wear.",
    price: 39.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=6",
  },
  {
    title: "Women's Jacket",
    description: "Stylish lightweight jacket.",
    price: 69.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=7",
  },
  {
    title: "Running Shoes",
    description: "Breathable sports shoes for running.",
    price: 89.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=8",
  },
  {
    title: "Leather Wallet",
    description: "Premium genuine leather wallet.",
    price: 29.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=9",
  },
  {
    title: "Classic Sunglasses",
    description: "UV-protected stylish sunglasses.",
    price: 24.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=10",
  },
  {
    title: "Coffee Maker",
    description: "Automatic drip coffee machine.",
    price: 79.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=11",
  },
  {
    title: "Vacuum Cleaner",
    description: "Powerful bagless vacuum cleaner.",
    price: 139.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=12",
  },
  {
    title: "LED Desk Lamp",
    description: "Adjustable brightness desk lamp.",
    price: 27.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=13",
  },
  {
    title: "Wall Clock",
    description: "Modern silent wall clock.",
    price: 22.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=14",
  },
  {
    title: "Throw Pillow",
    description: "Soft decorative cushion.",
    price: 16.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=15",
  },
  {
    title: "Yoga Mat",
    description: "Non-slip exercise yoga mat.",
    price: 31.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=16",
  },
  {
    title: "Football",
    description: "Official size training football.",
    price: 25.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=17",
  },
  {
    title: "Tennis Racket",
    description: "Lightweight professional racket.",
    price: 89.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=18",
  },
  {
    title: "Camping Tent",
    description: "4-person waterproof camping tent.",
    price: 159.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=19",
  },
  {
    title: "Dumbbell Set",
    description: "Adjustable home workout dumbbells.",
    price: 119.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=20",
  },
  {
    title: "Cookbook",
    description: "Delicious recipes from around the world.",
    price: 18.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=21",
  },
  {
    title: "JavaScript Guide",
    description: "Complete JavaScript programming book.",
    price: 34.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=22",
  },
  {
    title: "Notebook",
    description: "Hardcover lined notebook.",
    price: 9.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=23",
  },
  {
    title: "Fantasy Novel",
    description: "Epic fantasy adventure story.",
    price: 14.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=24",
  },
  {
    title: "Children's Story Book",
    description: "Illustrated bedtime stories.",
    price: 12.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=25",
  },
  {
    title: "Lipstick Set",
    description: "Long-lasting matte lipstick collection.",
    price: 24.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=26",
  },
  {
    title: "Face Wash",
    description: "Gentle daily facial cleanser.",
    price: 14.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=27",
  },
  {
    title: "Perfume",
    description: "Fresh floral fragrance.",
    price: 49.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=28",
  },
  {
    title: "Hair Dryer",
    description: "Professional salon hair dryer.",
    price: 54.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=29",
  },
  {
    title: "Skin Care Kit",
    description: "Complete daily skincare routine.",
    price: 69.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=30",
  },
  {
    title: "Toy Car",
    description: "Die-cast collectible toy car.",
    price: 11.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=31",
  },
  {
    title: "Building Blocks",
    description: "Creative construction toy set.",
    price: 39.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=32",
  },
  {
    title: "Stuffed Teddy Bear",
    description: "Soft plush teddy bear.",
    price: 21.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=33",
  },
  {
    title: "Puzzle Game",
    description: "1000-piece family puzzle.",
    price: 19.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=34",
  },
  {
    title: "Remote Control Drone",
    description: "Beginner-friendly camera drone.",
    price: 199.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=35",
  },
  {
    title: "Office Chair",
    description: "Ergonomic adjustable office chair.",
    price: 179.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=36",
  },
  {
    title: "Wooden Study Desk",
    description: "Minimalist wooden computer desk.",
    price: 249.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=37",
  },
  {
    title: "Bookshelf",
    description: "5-tier wooden bookshelf.",
    price: 129.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=38",
  },
  {
    title: "Dining Chair",
    description: "Comfortable modern dining chair.",
    price: 79.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=39",
  },
  {
    title: "Bean Bag",
    description: "Large soft bean bag for relaxing.",
    price: 59.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=40",
  },
  {
    title: "Apple MacBook Air M3 13-inch Laptop with 16GB RAM and 512GB SSD Storage",
    description: "Powerful Apple MacBook Air featuring the M3 chip, 16GB unified memory, 512GB SSD, Retina display, lightweight aluminum design, all-day battery life, perfect for students, developers, designers, and professionals.",
    price: 1499.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=41",
  },
  {
    title: "Samsung Galaxy S25 Ultra 512GB 5G Android Smartphone with AMOLED Display",
    description: "Premium Samsung Galaxy smartphone with 200MP camera, Snapdragon processor, S Pen support, long-lasting battery, ultra-fast charging, 5G connectivity, and stunning AMOLED display.",
    price: 1399.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=42",
  },
  {
    title: "Sony WH-1000XM6 Premium Wireless Noise Cancelling Bluetooth Headphones",
    description: "Industry-leading active noise cancellation headphones with crystal-clear audio, premium comfort, long battery life, Bluetooth 5.4 connectivity, and fast charging support.",
    price: 399.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=43",
  },
  {
    title: "Men's Premium Slim Fit Cotton Casual Shirt with Full Sleeves",
    description: "Comfortable and breathable slim-fit cotton shirt designed for office wear, business meetings, casual outings, and everyday fashion with wrinkle-resistant fabric.",
    price: 39.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=44",
  },
  {
    title: "Women's Elegant Floral Printed Maxi Dress for Summer and Casual Wear",
    description: "Beautiful floral maxi dress made from lightweight breathable fabric, featuring a stylish fit, soft texture, and elegant design suitable for parties, vacations, and daily wear.",
    price: 64.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=45",
  },
  {
    title: "Professional Adjustable Ergonomic Office Chair with Lumbar Support",
    description: "Modern office chair featuring adjustable height, breathable mesh back, comfortable lumbar support, padded armrests, smooth rolling wheels, and ergonomic seating for long work hours.",
    price: 229.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=46",
  },
  {
    title: "Modern Wooden TV Entertainment Unit with Storage Cabinets and Shelves",
    description: "Elegant wooden TV stand featuring spacious storage cabinets, open shelves, scratch-resistant finish, and modern minimalist design for living rooms and entertainment setups.",
    price: 299.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=47",
  },
  {
    title: "Premium Stainless Steel Cookware Set with Non-Stick Frying Pan Collection",
    description: "Complete cookware set including frying pans, saucepans, stockpot, and tempered glass lids with durable stainless steel construction and non-stick coating.",
    price: 179.99,
    category: "Kitchen",
    image: "https://picsum.photos/300/300?random=48",
  },
  {
    title: "Professional DSLR Camera Backpack with Waterproof Laptop Compartment",
    description: "Spacious waterproof camera backpack featuring padded compartments for DSLR cameras, lenses, drone accessories, tripod holder, and dedicated laptop storage.",
    price: 89.99,
    category: "Accessories",
    image: "https://picsum.photos/300/300?random=49",
  },
  {
    title: "Smart Home WiFi Security Camera with Night Vision and Motion Detection",
    description: "1080p HD indoor security camera featuring AI motion detection, two-way audio, cloud storage support, infrared night vision, and smartphone app control.",
    price: 79.99,
    category: "Smart Home",
    image: "https://picsum.photos/300/300?random=50",
  },
  {
    title: "Professional Gaming Mouse with RGB Lighting and Adjustable DPI Settings",
    description: "High-performance gaming mouse featuring customizable RGB lighting, programmable buttons, ergonomic grip, adjustable DPI up to 26000, and ultra-fast response time.",
    price: 69.99,
    category: "Gaming",
    image: "https://picsum.photos/300/300?random=51",
  },
  {
    title: "Ultra HD 4K Smart Android LED Television with Voice Remote Control",
    description: "55-inch Ultra HD Smart TV with HDR support, Android operating system, voice assistant integration, streaming apps, WiFi connectivity, and immersive surround sound.",
    price: 799.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=52",
  },
  {
    title: "Premium Leather Travel Duffel Bag with Shoe Compartment and Laptop Sleeve",
    description: "Stylish genuine leather travel bag featuring spacious storage, dedicated shoe compartment, padded laptop sleeve, adjustable shoulder strap, and premium craftsmanship.",
    price: 129.99,
    category: "Travel",
    image: "https://picsum.photos/300/300?random=53",
  },
  {
    title: "Luxury Memory Foam Orthopedic Mattress Topper for Better Sleep Comfort",
    description: "High-density memory foam mattress topper providing pressure relief, back support, cooling comfort, breathable fabric, and enhanced sleeping experience.",
    price: 159.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=54",
  },
  {
    title: "Professional Makeup Kit with Eyeshadow Palette, Brushes, and Lip Colors",
    description: "Complete makeup kit including highly pigmented eyeshadows, premium brushes, lipsticks, blushes, contour shades, and long-lasting cosmetics for beginners and professionals.",
    price: 99.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=55",
  },
  {
    title: "Mountain Bicycle with Aluminum Frame, Hydraulic Disc Brakes, and 21-Speed Gear",
    description: "Durable mountain bike featuring lightweight aluminum frame, front suspension, hydraulic disc brakes, 21-speed gear system, and all-terrain performance.",
    price: 699.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=56",
  },
  {
    title: "Complete JavaScript and React Development Bootcamp for Modern Web Applications",
    description: "Comprehensive programming course covering JavaScript ES6, React, Next.js, Node.js, REST APIs, MongoDB, authentication, deployment, and full-stack development projects.",
    price: 59.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=57",
  },
  {
    title: "Luxury Automatic Espresso Coffee Machine with Milk Frother and Grinder",
    description: "Professional espresso machine featuring built-in grinder, milk frother, programmable settings, stainless steel construction, and café-quality coffee brewing.",
    price: 549.99,
    category: "Kitchen",
    image: "https://picsum.photos/300/300?random=58",
  },
  {
    title: "Premium Fitness Smart Band with Blood Oxygen Monitoring and GPS Tracking",
    description: "Advanced fitness tracker featuring heart rate monitoring, blood oxygen measurement, sleep tracking, GPS, waterproof design, and up to 14 days battery life.",
    price: 99.99,
    category: "Wearables",
    image: "https://picsum.photos/300/300?random=59",
  },
  {
    title: "Portable External SSD 2TB USB-C High Speed Solid State Drive for Backup Storage",
    description: "Ultra-fast external SSD with USB-C connectivity, shock-resistant design, high-speed data transfer, reliable backup solution, and compatibility with Windows, macOS, and Linux.",
    price: 189.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=60",
  }
]);

  return Response.json({
    message: "Database seeded successfully",
  });
}