import connectDB from "@/lib/db";
import Product from "@/models/Product";

export async function GET() {
  await connectDB();

  await Product.deleteMany({});

  await Product.insertMany([
  {
    title: "Wireless Mouse",
    description: "Ergonomic wireless mouse with USB receiver.",
    price: 19.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=1",
  },
  {
    title: "Gaming Keyboard",
    description: "RGB mechanical gaming keyboard.",
    price: 59.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=2",
  },
  {
    title: "Bluetooth Speaker",
    description: "Portable waterproof Bluetooth speaker.",
    price: 34.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=3",
  },
  {
    title: "Noise Cancelling Headphones",
    description: "Premium over-ear wireless headphones.",
    price: 129.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=4",
  },
  {
    title: "Smart Watch",
    description: "Fitness tracking smartwatch with heart rate monitor.",
    price: 149.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=5",
  },
  {
    title: "Men's Hoodie",
    description: "Comfortable cotton hoodie for everyday wear.",
    price: 39.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=6",
  },
  {
    title: "Women's Jacket",
    description: "Stylish lightweight jacket.",
    price: 69.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=7",
  },
  {
    title: "Running Shoes",
    description: "Breathable sports shoes for running.",
    price: 89.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=8",
  },
  {
    title: "Leather Wallet",
    description: "Premium genuine leather wallet.",
    price: 29.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=9",
  },
  {
    title: "Classic Sunglasses",
    description: "UV-protected stylish sunglasses.",
    price: 24.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=10",
  },
  {
    title: "Coffee Maker",
    description: "Automatic drip coffee machine.",
    price: 79.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=11",
  },
  {
    title: "Vacuum Cleaner",
    description: "Powerful bagless vacuum cleaner.",
    price: 139.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=12",
  },
  {
    title: "LED Desk Lamp",
    description: "Adjustable brightness desk lamp.",
    price: 27.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=13",
  },
  {
    title: "Wall Clock",
    description: "Modern silent wall clock.",
    price: 22.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=14",
  },
  {
    title: "Throw Pillow",
    description: "Soft decorative cushion.",
    price: 16.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=15",
  },
  {
    title: "Yoga Mat",
    description: "Non-slip exercise yoga mat.",
    price: 31.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=16",
  },
  {
    title: "Football",
    description: "Official size training football.",
    price: 25.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=17",
  },
  {
    title: "Tennis Racket",
    description: "Lightweight professional racket.",
    price: 89.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=18",
  },
  {
    title: "Camping Tent",
    description: "4-person waterproof camping tent.",
    price: 159.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=19",
  },
  {
    title: "Dumbbell Set",
    description: "Adjustable home workout dumbbells.",
    price: 119.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=20",
  },
  {
    title: "Cookbook",
    description: "Delicious recipes from around the world.",
    price: 18.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=21",
  },
  {
    title: "JavaScript Guide",
    description: "Complete JavaScript programming book.",
    price: 34.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=22",
  },
  {
    title: "Notebook",
    description: "Hardcover lined notebook.",
    price: 9.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=23",
  },
  {
    title: "Fantasy Novel",
    description: "Epic fantasy adventure story.",
    price: 14.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=24",
  },
  {
    title: "Children's Story Book",
    description: "Illustrated bedtime stories.",
    price: 12.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=25",
  },
  {
    title: "Lipstick Set",
    description: "Long-lasting matte lipstick collection.",
    price: 24.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=26",
  },
  {
    title: "Face Wash",
    description: "Gentle daily facial cleanser.",
    price: 14.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=27",
  },
  {
    title: "Perfume",
    description: "Fresh floral fragrance.",
    price: 49.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=28",
  },
  {
    title: "Hair Dryer",
    description: "Professional salon hair dryer.",
    price: 54.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=29",
  },
  {
    title: "Skin Care Kit",
    description: "Complete daily skincare routine.",
    price: 69.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=30",
  },
  {
    title: "Toy Car",
    description: "Die-cast collectible toy car.",
    price: 11.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=31",
  },
  {
    title: "Building Blocks",
    description: "Creative construction toy set.",
    price: 39.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=32",
  },
  {
    title: "Stuffed Teddy Bear",
    description: "Soft plush teddy bear.",
    price: 21.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=33",
  },
  {
    title: "Puzzle Game",
    description: "1000-piece family puzzle.",
    price: 19.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=34",
  },
  {
    title: "Remote Control Drone",
    description: "Beginner-friendly camera drone.",
    price: 199.99,
    category: "Toys",
    image: "https://picsum.photos/300/300?random=35",
  },
  {
    title: "Office Chair",
    description: "Ergonomic adjustable office chair.",
    price: 179.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=36",
  },
  {
    title: "Wooden Study Desk",
    description: "Minimalist wooden computer desk.",
    price: 249.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=37",
  },
  {
    title: "Bookshelf",
    description: "5-tier wooden bookshelf.",
    price: 129.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=38",
  },
  {
    title: "Dining Chair",
    description: "Comfortable modern dining chair.",
    price: 79.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=39",
  },
  {
    title: "Bean Bag",
    description: "Large soft bean bag for relaxing.",
    price: 59.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=40",
  },
  {
    title: "Apple MacBook Air M3 13-inch Laptop with 16GB RAM and 512GB SSD Storage",
    description: "Powerful Apple MacBook Air featuring the M3 chip, 16GB unified memory, 512GB SSD, Retina display, lightweight aluminum design, all-day battery life, perfect for students, developers, designers, and professionals.",
    price: 1499.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=41",
  },
  {
    title: "Samsung Galaxy S25 Ultra 512GB 5G Android Smartphone with AMOLED Display",
    description: "Premium Samsung Galaxy smartphone with 200MP camera, Snapdragon processor, S Pen support, long-lasting battery, ultra-fast charging, 5G connectivity, and stunning AMOLED display.",
    price: 1399.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=42",
  },
  {
    title: "Sony WH-1000XM6 Premium Wireless Noise Cancelling Bluetooth Headphones",
    description: "Industry-leading active noise cancellation headphones with crystal-clear audio, premium comfort, long battery life, Bluetooth 5.4 connectivity, and fast charging support.",
    price: 399.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=43",
  },
  {
    title: "Men's Premium Slim Fit Cotton Casual Shirt with Full Sleeves",
    description: "Comfortable and breathable slim-fit cotton shirt designed for office wear, business meetings, casual outings, and everyday fashion with wrinkle-resistant fabric.",
    price: 39.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=44",
  },
  {
    title: "Women's Elegant Floral Printed Maxi Dress for Summer and Casual Wear",
    description: "Beautiful floral maxi dress made from lightweight breathable fabric, featuring a stylish fit, soft texture, and elegant design suitable for parties, vacations, and daily wear.",
    price: 64.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=45",
  },
  {
    title: "Professional Adjustable Ergonomic Office Chair with Lumbar Support",
    description: "Modern office chair featuring adjustable height, breathable mesh back, comfortable lumbar support, padded armrests, smooth rolling wheels, and ergonomic seating for long work hours.",
    price: 229.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=46",
  },
  {
    title: "Modern Wooden TV Entertainment Unit with Storage Cabinets and Shelves",
    description: "Elegant wooden TV stand featuring spacious storage cabinets, open shelves, scratch-resistant finish, and modern minimalist design for living rooms and entertainment setups.",
    price: 299.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=47",
  },
  {
    title: "Premium Stainless Steel Cookware Set with Non-Stick Frying Pan Collection",
    description: "Complete cookware set including frying pans, saucepans, stockpot, and tempered glass lids with durable stainless steel construction and non-stick coating.",
    price: 179.99,
    category: "Kitchen",
    image: "https://picsum.photos/300/300?random=48",
  },
  {
    title: "Professional DSLR Camera Backpack with Waterproof Laptop Compartment",
    description: "Spacious waterproof camera backpack featuring padded compartments for DSLR cameras, lenses, drone accessories, tripod holder, and dedicated laptop storage.",
    price: 89.99,
    category: "Accessories",
    image: "https://picsum.photos/300/300?random=49",
  },
  {
    title: "Smart Home WiFi Security Camera with Night Vision and Motion Detection",
    description: "1080p HD indoor security camera featuring AI motion detection, two-way audio, cloud storage support, infrared night vision, and smartphone app control.",
    price: 79.99,
    category: "Smart Home",
    image: "https://picsum.photos/300/300?random=50",
  },
  {
    title: "Professional Gaming Mouse with RGB Lighting and Adjustable DPI Settings",
    description: "High-performance gaming mouse featuring customizable RGB lighting, programmable buttons, ergonomic grip, adjustable DPI up to 26000, and ultra-fast response time.",
    price: 69.99,
    category: "Gaming",
    image: "https://picsum.photos/300/300?random=51",
  },
  {
    title: "Ultra HD 4K Smart Android LED Television with Voice Remote Control",
    description: "55-inch Ultra HD Smart TV with HDR support, Android operating system, voice assistant integration, streaming apps, WiFi connectivity, and immersive surround sound.",
    price: 799.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=52",
  },
  {
    title: "Premium Leather Travel Duffel Bag with Shoe Compartment and Laptop Sleeve",
    description: "Stylish genuine leather travel bag featuring spacious storage, dedicated shoe compartment, padded laptop sleeve, adjustable shoulder strap, and premium craftsmanship.",
    price: 129.99,
    category: "Travel",
    image: "https://picsum.photos/300/300?random=53",
  },
  {
    title: "Luxury Memory Foam Orthopedic Mattress Topper for Better Sleep Comfort",
    description: "High-density memory foam mattress topper providing pressure relief, back support, cooling comfort, breathable fabric, and enhanced sleeping experience.",
    price: 159.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=54",
  },
  {
    title: "Professional Makeup Kit with Eyeshadow Palette, Brushes, and Lip Colors",
    description: "Complete makeup kit including highly pigmented eyeshadows, premium brushes, lipsticks, blushes, contour shades, and long-lasting cosmetics for beginners and professionals.",
    price: 99.99,
    category: "Beauty",
    image: "https://picsum.photos/300/300?random=55",
  },
  {
    title: "Mountain Bicycle with Aluminum Frame, Hydraulic Disc Brakes, and 21-Speed Gear",
    description: "Durable mountain bike featuring lightweight aluminum frame, front suspension, hydraulic disc brakes, 21-speed gear system, and all-terrain performance.",
    price: 699.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=56",
  },
  {
    title: "Complete JavaScript and React Development Bootcamp for Modern Web Applications",
    description: "Comprehensive programming course covering JavaScript ES6, React, Next.js, Node.js, REST APIs, MongoDB, authentication, deployment, and full-stack development projects.",
    price: 59.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=57",
  },
  {
    title: "Luxury Automatic Espresso Coffee Machine with Milk Frother and Grinder",
    description: "Professional espresso machine featuring built-in grinder, milk frother, programmable settings, stainless steel construction, and café-quality coffee brewing.",
    price: 549.99,
    category: "Kitchen",
    image: "https://picsum.photos/300/300?random=58",
  },
  {
    title: "Premium Fitness Smart Band with Blood Oxygen Monitoring and GPS Tracking",
    description: "Advanced fitness tracker featuring heart rate monitoring, blood oxygen measurement, sleep tracking, GPS, waterproof design, and up to 14 days battery life.",
    price: 99.99,
    category: "Wearables",
    image: "https://picsum.photos/300/300?random=59",
  },
  {
    title: "Portable External SSD 2TB USB-C High Speed Solid State Drive for Backup Storage",
    description: "Ultra-fast external SSD with USB-C connectivity, shock-resistant design, high-speed data transfer, reliable backup solution, and compatibility with Windows, macOS, and Linux.",
    price: 189.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=60",
  },
  {
    title: "Dell XPS 15 Ultra Performance Laptop with Intel Core Ultra 9, 32GB RAM and 1TB NVMe SSD",
    description: "Experience exceptional productivity with this premium Dell XPS laptop featuring a stunning OLED display, Intel Core Ultra processor, ultra-fast SSD storage, advanced cooling system, and long-lasting battery life for professionals and creators.",
    price: 1899.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=61",
  },
  {
    title: "Apple iPad Pro 13-inch M4 Chip Tablet with Liquid Retina XDR Display and Apple Pencil Support",
    description: "Powerful Apple iPad Pro featuring the latest M4 processor, ultra-bright Retina display, Face ID security, all-day battery, Apple Pencil compatibility, and professional-grade performance for work and creativity.",
    price: 1299.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=62",
  },
  {
    title: "Canon EOS R8 Full Frame Mirrorless Digital Camera with 24-50mm Lens Kit",
    description: "Capture stunning photos and cinematic 4K videos using this Canon mirrorless camera featuring advanced autofocus, full-frame sensor, image stabilization, and lightweight travel-friendly design.",
    price: 1599.99,
    category: "Photography",
    image: "https://picsum.photos/300/300?random=63",
  },
  {
    title: "Premium Adjustable Electric Standing Desk with Memory Height Presets and Cable Management",
    description: "Modern electric standing desk featuring dual motors, programmable height settings, durable wooden tabletop, cable organization, and ergonomic design for home and office productivity.",
    price: 499.99,
    category: "Furniture",
    image: "https://picsum.photos/300/300?random=64",
  },
  {
    title: "Nike Air Zoom Pegasus Premium Lightweight Running Shoes for Men with Cushioned Comfort",
    description: "High-performance running shoes offering breathable mesh upper, responsive Zoom Air cushioning, durable rubber outsole, lightweight comfort, and superior grip for daily training.",
    price: 159.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=65",
  },
  {
    title: "Women's Luxury Genuine Leather Crossbody Handbag with Gold Hardware and Adjustable Strap",
    description: "Elegant designer-inspired leather handbag featuring spacious compartments, premium craftsmanship, secure zipper closure, adjustable shoulder strap, and timeless fashion styling.",
    price: 119.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=66",
  },
  {
    title: "Professional Stainless Steel Kitchen Knife Set with Wooden Storage Block and Sharpener",
    description: "Complete kitchen knife collection including chef knife, bread knife, utility knife, paring knife, scissors, sharpening tool, and premium wooden storage block.",
    price: 149.99,
    category: "Kitchen",
    image: "https://picsum.photos/300/300?random=67",
  },
  {
    title: "Smart Robot Vacuum Cleaner with AI Navigation, Self-Charging Dock and WiFi App Control",
    description: "Advanced robotic vacuum featuring intelligent room mapping, automatic obstacle avoidance, powerful suction, scheduled cleaning, smartphone control, and voice assistant compatibility.",
    price: 449.99,
    category: "Smart Home",
    image: "https://picsum.photos/300/300?random=68",
  },
  {
    title: "Premium Organic Green Tea Collection with Antioxidants and Natural Herbal Ingredients",
    description: "Refreshing organic green tea made from premium hand-picked leaves, rich in antioxidants, supporting healthy lifestyle, improved metabolism, and delicious natural flavor.",
    price: 24.99,
    category: "Food",
    image: "https://picsum.photos/300/300?random=69",
  },
  {
    title: "Advanced Gaming Mechanical Keyboard with RGB Backlighting and Hot Swappable Switches",
    description: "Professional gaming keyboard featuring customizable RGB lighting, mechanical switches, anti-ghosting technology, durable aluminum frame, USB-C connectivity, and premium typing experience.",
    price: 139.99,
    category: "Gaming",
    image: "https://picsum.photos/300/300?random=70",
  },
  {
    title: "Professional Cordless Power Drill Kit with Lithium Battery, Charger and 50-Piece Accessory Set",
    description: "Versatile cordless drill featuring high-torque motor, rechargeable lithium battery, variable speed control, LED work light, and complete toolkit for DIY projects.",
    price: 169.99,
    category: "Tools",
    image: "https://picsum.photos/300/300?random=71",
  },
  {
    title: "Luxury Hotel Collection 1000 Thread Count Egyptian Cotton Bed Sheet Set with Pillow Covers",
    description: "Ultra-soft Egyptian cotton bedding set featuring breathable fabric, wrinkle-resistant finish, deep pocket fitted sheet, and luxurious comfort for restful sleep.",
    price: 99.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=72",
  },
  {
    title: "Professional Adjustable Dumbbell and Weight Bench Complete Home Gym Workout Equipment Set",
    description: "Comprehensive fitness equipment including adjustable bench, dumbbells, heavy-duty steel frame, multiple incline positions, and durable construction for full-body strength training.",
    price: 699.99,
    category: "Sports",
    image: "https://picsum.photos/300/300?random=73",
  },
  {
    title: "Premium Pet Automatic Food and Water Dispenser with Smart Feeding Schedule and Large Capacity",
    description: "Smart pet feeder featuring programmable meal scheduling, large food storage capacity, automatic water dispenser, easy cleaning, and reliable feeding for cats and dogs.",
    price: 89.99,
    category: "Pet Supplies",
    image: "https://picsum.photos/300/300?random=74",
  },
  {
    title: "Professional Business Backpack with USB Charging Port, Anti-Theft Design and 17-inch Laptop Compartment",
    description: "Modern travel backpack featuring water-resistant fabric, anti-theft zipper pockets, USB charging port, padded laptop compartment, ergonomic shoulder straps, and spacious storage for work or travel.",
    price: 74.99,
    category: "Accessories",
    image: "https://picsum.photos/300/300?random=75",
  },
  {
    title: "Apple AirPods Pro 2nd Generation Wireless Earbuds with Active Noise Cancellation and MagSafe Charging Case",
    description: "Enjoy immersive sound quality with Apple AirPods Pro featuring Active Noise Cancellation, Transparency Mode, spatial audio, long battery life, sweat resistance, and seamless connectivity across Apple devices.",
    price: 249.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=76",
  },
  {
    title: "Samsung 27-inch 4K UHD IPS Computer Monitor with HDR10, USB-C and Ultra Slim Bezels",
    description: "Crystal-clear 4K UHD monitor featuring HDR10 support, vibrant IPS display, USB-C connectivity, ultra-thin bezels, eye comfort technology, and adjustable stand for work and entertainment.",
    price: 329.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=77",
  },
  {
    title: "Logitech MX Master 3S Advanced Wireless Bluetooth Mouse for Productivity and Creative Professionals",
    description: "Premium ergonomic wireless mouse featuring silent clicks, ultra-precise tracking, customizable buttons, USB-C fast charging, and multi-device connectivity for maximum productivity.",
    price: 109.99,
    category: "Electronics",
    image: "https://picsum.photos/300/300?random=78",
  },
  {
    title: "Men's Classic Denim Jacket with Soft Cotton Fabric and Stylish Button Front Design",
    description: "Premium denim jacket crafted from durable cotton fabric, featuring multiple pockets, comfortable fit, timeless style, and versatile everyday fashion for all seasons.",
    price: 69.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=79",
  },
  {
    title: "Women's Comfortable High Waist Stretch Denim Jeans with Modern Slim Fit Design",
    description: "Fashionable high-waisted jeans made with stretchable premium denim fabric, providing all-day comfort, flattering fit, durability, and versatile styling for casual outfits.",
    price: 54.99,
    category: "Fashion",
    image: "https://picsum.photos/300/300?random=80",
  },
  {
    title: "Premium Stainless Steel Double Wall Vacuum Insulated Water Bottle with Leakproof Lid",
    description: "Keep beverages hot for 12 hours or cold for 24 hours with this durable stainless steel insulated bottle featuring a leakproof cap and BPA-free construction.",
    price: 29.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=81",
  },
  {
    title: "Professional LED Ring Light with Adjustable Tripod Stand for Photography and Video Recording",
    description: "High-quality LED ring light featuring adjustable brightness, multiple color temperatures, smartphone holder, USB power, and sturdy tripod for content creators.",
    price: 59.99,
    category: "Photography",
    image: "https://picsum.photos/300/300?random=82",
  },
  {
    title: "Amazon Kindle Paperwhite Waterproof E-Reader with 16GB Storage and Adjustable Warm Light",
    description: "Read your favorite books anywhere with the Kindle Paperwhite featuring glare-free display, waterproof design, weeks of battery life, and adjustable warm lighting.",
    price: 169.99,
    category: "Books",
    image: "https://picsum.photos/300/300?random=83",
  },
  {
    title: "Professional Chef Non-Stick Aluminum Frying Pan with Heat Resistant Handle and Glass Lid",
    description: "Premium non-stick frying pan designed for healthy cooking, even heat distribution, scratch resistance, ergonomic handle, and compatibility with all stovetops.",
    price: 49.99,
    category: "Kitchen",
    image: "https://picsum.photos/300/300?random=84",
  },
  {
    title: "Premium Adjustable Office Desk Lamp with Wireless Charging Pad and USB Fast Charging Port",
    description: "Modern LED desk lamp featuring touch controls, adjustable brightness levels, eye protection technology, built-in wireless charging pad, and USB charging port.",
    price: 64.99,
    category: "Home",
    image: "https://picsum.photos/300/300?random=85",
  }
]);

  return Response.json({
    message: "Database seeded successfully",
  });
}